# Generated by Django 2.0.6 on 2019-04-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190425_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='choice_text',
            new_name='logradouro',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='votes',
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
